### ISSUE TITLE
Column color based on CSS

### ISSUE THREAD

**Issue by Reemh** [sgratzl/lineup.js#5]
In the current version the color can be specified using `color` for example `color: '#4daf4a'`.
It would be good if the color could be specified using CSS class, for example `color-class: 'green-class'`, or any other way where the used color could be used and changed easily somewhere else.

**Comment by sgratzl** [comment]
an alternative approach could be to  introduce some `data` attribute containing. e.g. `data-column="a"`. would be simpler to update.

**Comment by sgratzl** [comment]
usage: 
within the description provide an attribute: `cssClass`, e.g. `cssClass: "orange"`

styling, e.g., 
```css
div.orange {
        background-color: orange;
}
rect.bar.orange {
        fill: orange;
}
```
